### ISSUE TITLE
Impossible d'installer Crave

### ISSUE THREAD

**Issue by MartChic** [antoine-lombardo/plugin.video.crave#1]
J'essaie d'installer Crave sur un Raspberry Pi 3b (Libreelec) et ça me donne l'erreur "la dépendance de script.module.requests 2.25.1+ n'a pas pu être satisfaite". Le module est pourtant installé.

**Comment by antoine-lombardo** [comment]
Tu es sur quelle version de Kodi?

**Comment by MartChic** [comment]
18.9

**Comment by antoine-lombardo** [comment]
L’addon a été conçu pour Kodi Matrix, je vais essayer de mon côté de le faire fonctionner sur Leia et je te reviens!

**Comment by MartChic** [comment]
Super, merci.

**Comment by antoine-lombardo** [comment]
Après vérifications, impossible d'utiliser Python 3 sous Leia. Ce serait trop de travail de porter ce projet sous Python 2. Je t'invite à tenter d'installer Kodi Matrix!
